server:
  port: 9006
spring:
  application:
    name: hrm-page
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_page
      username: root
      password: 888666
mybatis-plus:
  mapper-locations: classpath:com/cch/hrm/mapper/*Mapper.xml
  type-aliases-package: com.cch.hrm.domain,com.cch.hrm.query